name: Test and publish
on:
  push:
    branches: [ git-utils-dr ]
#    paths:
#      - '!README.md'
#      - '!*.yml'
#      - '!art/**'
#      - '!build.gradle'
#      - '!build.gradle.kts'

jobs:
  unit-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Lint and tests
        run: |
          ./gradlew  git-utils:test git-utils-dr:test
      - name: 'Publish Plugin Test Report'
        if: always()
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'changelog-update-test-report'
          path: changelog-update/build/reports/tests/*